"""JStack-owned project intelligence backed by a pinned local Graphify runtime."""

from .protocol import (
    MANDATORY_WORKFLOWS,
    PROJECT_INTELLIGENCE_SCHEMA_VERSION,
    ProjectIntelligenceError,
    assess_applicability,
    build_snapshot,
    canonical_digest,
    catalog_digest,
    discover_provider,
    focused_query,
    graph_inventory,
    impact_analysis,
    is_supported_source_path,
    load_snapshot,
    load_current_snapshot,
    project_storage_root,
    provider_catalog,
    requires_graph_source_coverage,
    render_focused_graph,
    supported_source_count,
)

__all__ = [
    "MANDATORY_WORKFLOWS",
    "PROJECT_INTELLIGENCE_SCHEMA_VERSION",
    "ProjectIntelligenceError",
    "assess_applicability",
    "build_snapshot",
    "canonical_digest",
    "catalog_digest",
    "discover_provider",
    "focused_query",
    "graph_inventory",
    "impact_analysis",
    "is_supported_source_path",
    "load_snapshot",
    "load_current_snapshot",
    "project_storage_root",
    "provider_catalog",
    "requires_graph_source_coverage",
    "render_focused_graph",
    "supported_source_count",
]
