"""Durable, fail-closed loop-engineering protocol for JStack."""

from .protocol import (
    AUTONOMY_LEVELS,
    EXECUTION_MODES,
    GOAL_CONTEXT_SCHEMA,
    GOAL_DOMAIN_TAGS,
    GOAL_INFERRED_FIELDS,
    GOAL_READINESS_RECEIPT_SCHEMA,
    GOAL_READINESS_SCHEMA,
    LOOP_CONTRACT_SCHEMA,
    LOOP_EVENT_SCHEMA,
    LOOP_SNAPSHOT_SCHEMA,
    MAX_CONTEXT_SOURCES,
    MAX_OPEN_QUESTIONS,
    RISK_TIERS,
    LoopError,
    LoopService,
    assess_goal_readiness,
    goal_readiness_contract_digest,
)

__all__ = [
    "AUTONOMY_LEVELS",
    "EXECUTION_MODES",
    "GOAL_CONTEXT_SCHEMA",
    "GOAL_DOMAIN_TAGS",
    "GOAL_INFERRED_FIELDS",
    "GOAL_READINESS_RECEIPT_SCHEMA",
    "GOAL_READINESS_SCHEMA",
    "LOOP_CONTRACT_SCHEMA",
    "LOOP_EVENT_SCHEMA",
    "LOOP_SNAPSHOT_SCHEMA",
    "MAX_CONTEXT_SOURCES",
    "MAX_OPEN_QUESTIONS",
    "RISK_TIERS",
    "LoopError",
    "LoopService",
    "assess_goal_readiness",
    "goal_readiness_contract_digest",
]
