"""JStack Product Interface System contracts and evidence validation."""

from .detector import (
    detect_product_ui,
    detect_product_ui_scope,
    established_system_evidence_paths,
    is_established_system_path,
)
from .design import (
    DESIGN_CAPABILITY_IDS,
    DESIGN_DECISION_INPUT_SCHEMA_VERSION,
    DESIGN_DECISION_SCHEMA_VERSION,
    DESIGN_MODES,
    DESIGN_POLICY_SCHEMA_VERSION,
    DESIGN_POLICY_VERSION,
    DESIGN_PRECEDENCE,
    DesignDecisionError,
    build_design_decision,
    design_policy,
    validate_design_decision,
)
from .evidence import EvidenceError, load_and_validate_evidence
from .motion import (
    CATEGORY_IDS as MOTION_CATEGORY_IDS,
    FREQUENCY_IDS as MOTION_FREQUENCY_IDS,
    INPUT_MODE_IDS as MOTION_INPUT_MODE_IDS,
    MAX_INTERACTIONS as MOTION_MAX_INTERACTIONS,
    MAX_RUNTIME_EVIDENCE as MOTION_MAX_RUNTIME_EVIDENCE,
    MOTION_CATALOG_SCHEMA_VERSION,
    MOTION_CATALOG_VERSION,
    MOTION_RESPONSE_SCHEMA_VERSION,
    MOTION_SPEC_SCHEMA_VERSION,
    RUNTIME_STRATEGY_IDS as MOTION_RUNTIME_STRATEGY_IDS,
    MotionError,
    build_motion_spec,
    load_motion_catalog,
    validate_motion_catalog,
    validate_motion_spec,
)
from .motion_evidence import (
    CLS_LIMIT as MOTION_CLS_LIMIT,
    DROPPED_FRAME_RATIO_LIMIT as MOTION_DROPPED_FRAME_RATIO_LIMIT,
    FRAME_BUDGET_TOLERANCE_MS as MOTION_FRAME_BUDGET_TOLERANCE_MS,
    INPUT_FEEDBACK_LIMIT_MS as MOTION_INPUT_FEEDBACK_LIMIT_MS,
    LONG_TASK_LIMIT_MS as MOTION_LONG_TASK_LIMIT_MS,
    MAX_MANIFEST_BYTES as MOTION_MAX_EVIDENCE_MANIFEST_BYTES,
    MAX_RESULTS as MOTION_MAX_RESULTS,
    MOTION_AUDIT_SCHEMA_VERSION,
    MOTION_EVIDENCE_SCHEMA_VERSION,
    MOTION_FINALIZATION_RECEIPT_SCHEMA_VERSION,
    MOTION_FINALIZATION_SCHEMA_VERSION,
    MOTION_RESULT_SCHEMA_VERSION,
    MotionEvidenceError,
    load_and_validate_motion_evidence,
    render_motion_report,
    write_private_motion_report,
)
from .reference import (
    MAX_VARIANTS as REFERENCE_MAX_VARIANTS,
    MAX_VIEWPORTS as REFERENCE_MAX_VIEWPORTS,
    REFERENCE_BINDING_SCHEMA_VERSION,
    REFERENCE_BUNDLE_SCHEMA_VERSION,
    REFERENCE_CONTRACT_SCHEMA_VERSION,
    PROTOTYPE_MODES,
    SOURCE_KINDS,
    ReferenceError,
    build_reference_contract,
    load_and_validate_reference_bundle,
    reference_binding,
    validate_reference_contract,
)
from .registry import (
    CATALOG_SCHEMA_VERSION,
    CATALOG_VERSION,
    DESIGN_CONTRACT_SCHEMA_VERSION,
    OBJECTIVE_CHECK_KINDS,
    PROFILE_IDS,
    REFERENCE_DESIGN_CONTRACT_SCHEMA_VERSION,
    UIError,
    build_contract,
    canonical_bytes,
    canonical_digest,
    load_catalog,
    normalize_allowed_paths,
    normalize_reference_bundle,
    validate_contract,
)

__all__ = [
    "CATALOG_SCHEMA_VERSION",
    "CATALOG_VERSION",
    "DESIGN_CAPABILITY_IDS",
    "DESIGN_CONTRACT_SCHEMA_VERSION",
    "DESIGN_DECISION_INPUT_SCHEMA_VERSION",
    "DESIGN_DECISION_SCHEMA_VERSION",
    "DESIGN_MODES",
    "DESIGN_POLICY_SCHEMA_VERSION",
    "DESIGN_POLICY_VERSION",
    "DESIGN_PRECEDENCE",
    "OBJECTIVE_CHECK_KINDS",
    "PROFILE_IDS",
    "MOTION_CATALOG_SCHEMA_VERSION",
    "MOTION_CATALOG_VERSION",
    "MOTION_CATEGORY_IDS",
    "MOTION_CLS_LIMIT",
    "MOTION_DROPPED_FRAME_RATIO_LIMIT",
    "MOTION_EVIDENCE_SCHEMA_VERSION",
    "MOTION_FINALIZATION_RECEIPT_SCHEMA_VERSION",
    "MOTION_FINALIZATION_SCHEMA_VERSION",
    "MOTION_FRAME_BUDGET_TOLERANCE_MS",
    "MOTION_FREQUENCY_IDS",
    "MOTION_INPUT_MODE_IDS",
    "MOTION_INPUT_FEEDBACK_LIMIT_MS",
    "MOTION_LONG_TASK_LIMIT_MS",
    "MOTION_MAX_EVIDENCE_MANIFEST_BYTES",
    "MOTION_MAX_INTERACTIONS",
    "MOTION_MAX_RESULTS",
    "MOTION_MAX_RUNTIME_EVIDENCE",
    "MOTION_AUDIT_SCHEMA_VERSION",
    "MOTION_RESPONSE_SCHEMA_VERSION",
    "MOTION_RESULT_SCHEMA_VERSION",
    "MOTION_RUNTIME_STRATEGY_IDS",
    "MOTION_SPEC_SCHEMA_VERSION",
    "PROTOTYPE_MODES",
    "REFERENCE_BINDING_SCHEMA_VERSION",
    "REFERENCE_BUNDLE_SCHEMA_VERSION",
    "REFERENCE_CONTRACT_SCHEMA_VERSION",
    "REFERENCE_DESIGN_CONTRACT_SCHEMA_VERSION",
    "REFERENCE_MAX_VARIANTS",
    "REFERENCE_MAX_VIEWPORTS",
    "ReferenceError",
    "SOURCE_KINDS",
    "EvidenceError",
    "DesignDecisionError",
    "MotionError",
    "MotionEvidenceError",
    "UIError",
    "build_contract",
    "build_design_decision",
    "build_reference_contract",
    "build_motion_spec",
    "canonical_bytes",
    "canonical_digest",
    "detect_product_ui",
    "detect_product_ui_scope",
    "design_policy",
    "established_system_evidence_paths",
    "load_and_validate_evidence",
    "load_and_validate_motion_evidence",
    "load_and_validate_reference_bundle",
    "load_catalog",
    "load_motion_catalog",
    "is_established_system_path",
    "normalize_allowed_paths",
    "normalize_reference_bundle",
    "reference_binding",
    "render_motion_report",
    "validate_contract",
    "validate_design_decision",
    "validate_motion_catalog",
    "validate_motion_spec",
    "validate_reference_contract",
    "write_private_motion_report",
]
