"""JStack Product Interface System contracts and evidence validation."""

from .detector import (
    detect_product_ui,
    detect_product_ui_scope,
    established_system_evidence_paths,
    is_established_system_path,
)
from .evidence import EvidenceError, load_and_validate_evidence
from .motion import (
    CATEGORY_IDS as MOTION_CATEGORY_IDS,
    FREQUENCY_IDS as MOTION_FREQUENCY_IDS,
    INPUT_MODE_IDS as MOTION_INPUT_MODE_IDS,
    MAX_INTERACTIONS as MOTION_MAX_INTERACTIONS,
    MAX_RUNTIME_EVIDENCE as MOTION_MAX_RUNTIME_EVIDENCE,
    MOTION_CATALOG_SCHEMA_VERSION,
    MOTION_CATALOG_VERSION,
    MOTION_RESPONSE_SCHEMA_VERSION,
    MOTION_SPEC_SCHEMA_VERSION,
    RUNTIME_STRATEGY_IDS as MOTION_RUNTIME_STRATEGY_IDS,
    MotionError,
    build_motion_spec,
    load_motion_catalog,
    validate_motion_catalog,
    validate_motion_spec,
)
from .reference import (
    MAX_VARIANTS as REFERENCE_MAX_VARIANTS,
    MAX_VIEWPORTS as REFERENCE_MAX_VIEWPORTS,
    REFERENCE_BINDING_SCHEMA_VERSION,
    REFERENCE_BUNDLE_SCHEMA_VERSION,
    REFERENCE_CONTRACT_SCHEMA_VERSION,
    PROTOTYPE_MODES,
    SOURCE_KINDS,
    ReferenceError,
    build_reference_contract,
    load_and_validate_reference_bundle,
    reference_binding,
    validate_reference_contract,
)
from .registry import (
    CATALOG_SCHEMA_VERSION,
    CATALOG_VERSION,
    OBJECTIVE_CHECK_KINDS,
    PROFILE_IDS,
    UIError,
    build_contract,
    canonical_bytes,
    canonical_digest,
    load_catalog,
    normalize_allowed_paths,
    normalize_reference_bundle,
    validate_contract,
)

__all__ = [
    "CATALOG_SCHEMA_VERSION",
    "CATALOG_VERSION",
    "OBJECTIVE_CHECK_KINDS",
    "PROFILE_IDS",
    "MOTION_CATALOG_SCHEMA_VERSION",
    "MOTION_CATALOG_VERSION",
    "MOTION_CATEGORY_IDS",
    "MOTION_FREQUENCY_IDS",
    "MOTION_INPUT_MODE_IDS",
    "MOTION_MAX_INTERACTIONS",
    "MOTION_MAX_RUNTIME_EVIDENCE",
    "MOTION_RESPONSE_SCHEMA_VERSION",
    "MOTION_RUNTIME_STRATEGY_IDS",
    "MOTION_SPEC_SCHEMA_VERSION",
    "PROTOTYPE_MODES",
    "REFERENCE_BINDING_SCHEMA_VERSION",
    "REFERENCE_BUNDLE_SCHEMA_VERSION",
    "REFERENCE_CONTRACT_SCHEMA_VERSION",
    "REFERENCE_MAX_VARIANTS",
    "REFERENCE_MAX_VIEWPORTS",
    "ReferenceError",
    "SOURCE_KINDS",
    "EvidenceError",
    "MotionError",
    "UIError",
    "build_contract",
    "build_reference_contract",
    "build_motion_spec",
    "canonical_bytes",
    "canonical_digest",
    "detect_product_ui",
    "detect_product_ui_scope",
    "established_system_evidence_paths",
    "load_and_validate_evidence",
    "load_and_validate_reference_bundle",
    "load_catalog",
    "load_motion_catalog",
    "is_established_system_path",
    "normalize_allowed_paths",
    "normalize_reference_bundle",
    "reference_binding",
    "validate_contract",
    "validate_motion_catalog",
    "validate_motion_spec",
    "validate_reference_contract",
]
