"""JStack-native operating policy and deterministic Team Composer."""

from .mode_integration import (
    DEFAULT_UNIFIED_OS_MODE,
    UNIFIED_OS_MODES,
    ModeIntegrationError,
    authorized_write_scopes,
    build_request,
    coordination_packet,
    receipt_assignments,
    resolve_operating_profile,
    resolve_team_mode,
    team_plan_digest,
    unified_os_mode,
    validate_coordination_packet,
)

from .team_composer import (
    POLICY_SCHEMA_VERSION,
    POLICY_VERSION,
    REQUEST_SCHEMA_VERSION,
    TEAM_PLAN_SCHEMA_VERSION,
    TeamCompositionError,
    canonical_digest,
    compose_team,
    load_policy,
    policy_digest,
    policy_summary,
    semantic_team_plan_digest,
    validate_policy,
    validate_request,
    validate_team_plan,
)
from .delivery import (
    AUTHORITY_ARCHITECTURE_ID,
    EVIDENCE_SCHEMA_VERSION as DELIVERY_EVIDENCE_SCHEMA_VERSION,
    PIPELINE_SCHEMA_VERSION as DELIVERY_PIPELINE_SCHEMA_VERSION,
    STATUS_SCHEMA_VERSION as DELIVERY_STATUS_SCHEMA_VERSION,
    DeliveryContractError,
    build_delivery_pipeline,
    evaluate_delivery_evidence,
    normalize_phase_evidence,
    validate_delivery_pipeline,
)

__all__ = [
    "POLICY_SCHEMA_VERSION",
    "POLICY_VERSION",
    "REQUEST_SCHEMA_VERSION",
    "TEAM_PLAN_SCHEMA_VERSION",
    "DEFAULT_UNIFIED_OS_MODE",
    "UNIFIED_OS_MODES",
    "ModeIntegrationError",
    "TeamCompositionError",
    "canonical_digest",
    "authorized_write_scopes",
    "build_request",
    "compose_team",
    "coordination_packet",
    "load_policy",
    "policy_digest",
    "policy_summary",
    "receipt_assignments",
    "resolve_operating_profile",
    "resolve_team_mode",
    "semantic_team_plan_digest",
    "team_plan_digest",
    "unified_os_mode",
    "validate_coordination_packet",
    "validate_policy",
    "validate_request",
    "validate_team_plan",
    "AUTHORITY_ARCHITECTURE_ID",
    "DELIVERY_EVIDENCE_SCHEMA_VERSION",
    "DELIVERY_PIPELINE_SCHEMA_VERSION",
    "DELIVERY_STATUS_SCHEMA_VERSION",
    "DeliveryContractError",
    "build_delivery_pipeline",
    "evaluate_delivery_evidence",
    "normalize_phase_evidence",
    "validate_delivery_pipeline",
]
